# CHARTA {-}

Como se ha mencionado en la sección precedente, los documentos que hacen parte del COSUIZA son transcritos y editados conforme a los criterios establecidos por CHARTA.^[Para una exposición del proyecto ver @areta2014sin. Para acceder a la página del proyecto ir a <a href="https://www.redcharta.es/" target="_blank">https://www.redcharta.es/</a>. Para la página del corpus ir a <a href="https://www.corpuscharta.es/"target="_blank">https://www.corpuscharta.es/</a>.] Esta sigla tiene una doble significación: por una parte hace referencia a una <a href="https://www.redcharta.es/" target="_blank">red de investigación internacional</a> que nació en 2005 y, por otra, da el nombre al <a href="http://www.corpuscharta.es/" target="_blank">Corpus Hispánico y Americano en la Red: Textos Antiguos</a>.  
En primer lugar, el grupo estableció un estándar de edición aplicable a documentos de vertiente archivística con el propósito de uniformar las transcripciones de este tipo de documentos que suelen tener una alta dosis de subjetividad. En segundo lugar, se planteó la idea de constituir un corpus diacrónico (siglo XII al siglo XIX) de textos españoles e hispanoamericanos editados con los mencionados criterios y presentarlos en tres versiones: paleográfica, crítica y facsimilar.  
Las posibilidades ofrecidas por bases de datos como el corpus CHARTA han sido de enorme utilidad para las diferentes disciplinas que se interesan en la documentación histórica y no literaria. La creación y evolución de este corpus (y de sus subcorpus) está resultando de vital importancia para el estudio histórico de la lengua.
Sin embargo, la abundancia de datos textuales siempre plantea dificultades si las herramientas que utilizamos para el procesamiento de estos datos presentan limitaciones. No cabe duda que el acceso a grandes cantidades de datos textuales ha modificado el proceder metodológico de los lingüistas. Sus exigencias han evolucionado y desde hace un tiempo ya no es suficiente contar con datos disponibles en un mismo sitio en la red, ahora se hace necesario contar con herramientas capaces de procesar y manipular los datos textuales de modo que, por ejemplo, un fenómeno lingüístico pueda ser estudiado y analizado con ayuda de las computadoras y ya no solamente con la calma y perseverancia del lingüista tradicional.  En este contexto, herramientas digitales como el estándar de etiquetado TEI y la plataforma Teitok permiten la convergencia de la actividad ecdótica con la lingüística. Veremos en [§ TEITOK][teitok] las posibilidades que ofrece esta plaforma en este sentido.
También es necesario señalar que para llegar a construir fuentes de datos textuales fiables es indispensable el trabajo colaborativo de filólogos rigurosos dispuestos a revisar y corregir los datos que se ponen a disposición de la comunidad científica en estos corpus digitales. A este respecto, Teitok ofrece un entorno que facilita este trabajo colectivo. 

